### PR TITLE
Begin adding FastTurn methods

### PR DESCRIPTION
**Pull request by kawilliams8**
Here's the first draft of the FastRound and FastTurns methods... do we want or need to change which class is responsible for these tasks?

### CODE REVIEW

**Comment by djavanm** [comment]
Image from iOS

We can use this image as our starting point for the Fast Round and Fast Turn. I think we should continue the same ideas from our Full Round and Full Turn. However we made need to add a few of these new methods on game, and a new property for this.multiplier on the players.

**Comment by eoneill23** [comment]
I agree, Djavan. I think a lot (if not all) of the methods in FastRound will be similar to FullRound (start round that starts a new FastTurn, continueRound if both players haven't gone yet, endRound if both players have gone).

Do you have any ideas about the methods that we will need on our fast turn? We will probably need a timer - but what else?

**Comment by kawilliams8** [comment]
Yup, the timer will be on the Fast Turn, because it needs to be restarted for Player Two's Fast Round.

Which class should add the Fast Money score to the player's score property? In Player? Fast Turn?

**Comment by kawilliams8** [comment]
Do you guys think we need more inputs and buttons to handle the multiplier?

**Pull request merged**
